### ISSUE TITLE
Add "Hacktoberfest" to topics

### ISSUE THREAD

**Issue by TheNoim** [chetanraj/es-explorer#13]
You added two issues with the label Hacktoberfest. However, PR's only get counted if you add the topic "Hacktoberfest" to your repo. 

![Screen Shot 2020-10-03 at 14 29 06](https://user-images.githubusercontent.com/5133056/94991672-ce4e6c00-0584-11eb-87ea-2714bdcd8be2.png)

**Comment by chetanraj** [comment]
Hey @TheNoim, Thanks for letting me know. I have added the topic to the repo.

**Comment by TheNoim** [comment]
You're welcome.
